<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\RegistryRepair.Core\RegistryRepair.Core.csproj" />
    <ProjectReference Include="..\RegistryRepair.Windows\RegistryRepair.Windows.csproj" />
  </ItemGroup>
</Project>
